"""The checked-in CLI documentation is generated from the help tables."""

import io
import sys
import unittest

import gaxi
from gaxi import docsgen
from gaxi.helpdoc import COMMANDS


class DocumentationTest(unittest.TestCase):
    def test_every_command_is_documented(self) -> None:
        text = docsgen.generate()
        for name in COMMANDS:
            assert f"## {name}" in text

    def test_the_header_names_the_generator(self) -> None:
        text = docsgen.generate()
        assert text.startswith("# gaxi CLI")
        assert "Generated by `uv run invoke docs`" in text
        assert "Semantic policy bundle" in text

    def test_the_documentation_does_not_carry_the_release_version(self) -> None:
        # The version lives in pyproject.toml alone, so a bump cannot stale these docs.
        assert gaxi.__version__ not in docsgen.generate()

    def test_option_tables_escape_pipes(self) -> None:
        rows = docsgen._options_table([("--x", "a|b", "none", "Pick one.")])
        assert rows[0].startswith("| option |")
        assert r"a\|b" in rows[-1]

    def test_exit_codes_are_documented(self) -> None:
        text = docsgen.generate()
        assert "## Exit codes" in text
        assert "| 2 | unknown command or option" in text

    def test_main_writes_the_document_to_stdout(self) -> None:
        stream = io.StringIO()
        original, sys.stdout = sys.stdout, stream
        try:
            code = docsgen.main()
        finally:
            sys.stdout = original
        assert code == 0
        assert stream.getvalue() == docsgen.generate()
