"""Generate the checked-in CLI documentation from the help tables."""

from __future__ import annotations

import sys
from typing import TYPE_CHECKING

from gaxi.helpdoc import COMMANDS, GLOBAL_OPTIONS, format_help
from gaxi.policy_data import BUNDLE_VERSION

if TYPE_CHECKING:
    from gaxi.helpdoc import Option


def _options_table(options: list[Option]) -> list[str]:
    lines = ["| option | value | default | description |", "|---|---|---|---|"]
    for name, value, default, description in options:
        cell = value.replace("|", "\\|")
        lines.append(f"| `{name}` | {cell} | {default} | {description} |")
    return lines


def generate() -> str:
    """Render the checked-in CLI documentation."""
    lines = [
        "# gaxi CLI",
        "",
        (f"Semantic policy bundle {BUNDLE_VERSION}; "
        "instance descriptions: Swagger 2.0."),
        "",
        "Generated by `uv run invoke docs`. Do not edit by hand.",
        "",
        "## Global options",
        "",
    ]
    lines.extend(_options_table(GLOBAL_OPTIONS))
    lines.append("")
    for name, spec in COMMANDS.items():
        lines.extend([
            f"## {name}",
            "",
            spec["summary"],
            "",
            "```text",
            format_help(spec["usage"]),
            "```",
            "",
            f"Output: {spec['output']}",
            "",
        ])
        if spec["options"]:
            lines.extend(_options_table(spec["options"]))
            lines.append("")
        lines.append("Examples:")
        lines.append("")
        lines.append("```text")
        lines.extend(format_help(example) for example in spec["examples"])
        lines.append("```")
        lines.append("")
    lines.extend([
        "## Exit codes",
        "",
        "| code | meaning |",
        "|---|---|",
        "| 0 | success |",
        "| 1 | ordinary failure, including HTTP failures and missing acknowledgement |",
        "| 2 | unknown command or option, or input rejected before a request was sent |",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    """Write the documentation to stdout."""
    sys.stdout.write(generate())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
